version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      image: sentiment:latest

    container_name: app
    environment:
      - API_KEY=your-key
    ports:
      - "5000:5000"
    restart: unless-stopped
